version: '3.8'
services:
  application:
    build:
      context: 'Docker/Php'
    container_name: php-application
    volumes:
      - './Application:/srv'
      - './Docker/Php/php.ini:/usr/local/etc/php/conf.d/php.ini'
  nginx:
    build:
      context: 'Docker/Nginx'
    container_name: php-nginx
    volumes:
      - './Docker/Nginx/conf.d:/etc/nginx/conf.d'
      - './Application:/srv'
    ports:
      - '80:80'
      - '443:443'
  database:
    build:
      context: 'Docker/Mongo'
    container_name: php-database
    volumes:
      - 'symfony-db:/data/db'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE}
volumes:
  symfony-db: